language: rust

dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - rustup target add asmjs-unknown-emscripten
  - cargo install cargo-web
  - cargo web test --nodejs
