language: rust

dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly

env:
  - TARGET=wasm32-unknown-unknown
  - TARGET=asmjs-unknown-emscripten
  - TARGET=wasm32-unknown-emscripten

script:
  - nvm install 9
  - ./ci.sh
