[target.emscripten]
prepend-js = ["src/webcore/runtime.js", "src/webcore/runtime_emscripten.js"]

[target.wasm32-unknown-unknown]
prepend-js = ["src/webcore/runtime.js", "src/webcore/runtime_wasm.js"]
