[package]
name = "hasher"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = { path = "../.." }
stdweb-macros = { path = "../../stdweb-macros" }
sha1 = "0.3"
